src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255, maxMessage="255 caractères maximum autorisés.")
     */
    private $label;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $done;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Employee", inversedBy="tasks")
     */
    private $employee;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getDone(): ?bool
    {
        return $this->done;
    }

    public function setDone(bool $done): self
    {
        $this->done = $done;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self
    {
        $this->employee = $employee;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use App\Entity\Task;
use App\Entity\User;
use Doctrine\DBAL\Types\BooleanType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label', TextType::class, [
                "label" => false,
                "attr" => [
                    "class" => "form-control",
                    "placeholder" => "Libellé (Ex: Manger des alpagas extraterrestres)"
                ]
            ])
            ->add('start_at', TextType::class, [
                "label" => false,
                "attr" => [
                    "class" => "form-control datetimePicker",
                    "placeholder" => "Début (Ex: 2019-03-10 15:30)"
                ]
            ])
            ->add('end_at', TextType::class, [
                "label" => false,
                "attr" => [
                    "class" => "form-control datetimePicker",
                    "placeholder" => "Fin (Ex: 2019-03-10 15:30)"
                ]
            ])
            ->add('done', CheckboxType::class, [
                "required" => false,
                "label" => "Terminé",
                "attr" => [
                    "class" => "custom-select"
                ]
            ])
            ->add('employee', EntityType::class, [
                "class" => Employee::class,
                "label" => "Employé",
                "attr" => [
                    "class" => "custom-select"
                ]
            ])
            ->add('created_by', EntityType::class, [
                "class" => User::class,
                "label" => "Admin",
                "attr" => [
                    "class" => "custom-select"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('admin_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/task/edit.html.twig
<div class="d-flex flex-column align-items-center">

    <h1>Edition de la tâche {{ task.id }}</h1>

    <div class="form-container w-50 p-4 rounded">
        {{ form_start(form) }}
        {{ form_row(form._token) }}
        {% if moreError is not empty %}<span class="alert alert-danger">{{ moreError }}</span>{% endif %}

        <div class="form-group mt-4">
            {{ form_widget(form.label) }}
        </div>
        <div class="form-group">
            <!-- Pour start_at et end_at ce format est utilisé pour transformer les datetime en string -->
            <div class="input-group">
                <input type="text"
                       class="form-control datetimePicker"
                       name="task[{{ form.start_at.vars.name }}]"
                       value="{{ form.start_at.vars.value | date("Y/m/d H:i") }}"
                       placeholder="{{ form.start_at.vars.attr.placeholder ?? "" }}"
                />
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon1">
                        <img width="16" height="16" src="{{ asset('images/_ionicons_svg_md-calendar.svg') }}"/>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input type="text"
                       class="form-control datetimePicker"
                       name="task[{{ form.end_at.vars.name }}]"
                       value="{{ form.end_at.vars.value | date("Y/m/d H:i") }}"
                       placeholder="{{ form.end_at.vars.attr.placeholder ?? "" }}"
                />
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon1">
                        <img width="16" height="16" src="{{ asset('images/_ionicons_svg_md-calendar.svg') }}"/>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            {{ form_row(form.employee) }}
        </div>
        <div class="form-group">
            {{ form_row(form.created_by) }}
        </div>

        <button class="btn btn-success">{{ button_label|default('Save') }}</button>

        {{ form_end(form, { "render_rest": false }) }}
    </div>

    <a href="{{ path('admin_list') }}">back to list</a>
    {{ include('task/_delete_form.html.twig') }}
</div>

templates/task/index.html.twig
<div class="d-flex flex-row justify-content-center pt-4">
    <div class="d-flex flex-column align-items-center">

        <h1 class="align-self-start">Liste des tâches</h1>
        <a href="{{ path('admin_create') }}" class="btn btn-success align-self-start">Créer une tâche</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Libellé</th>
                    <th>Employé</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th>Terminé</th>
                </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
                <tr onclick="location.href='{{ path('admin_edit', {id: task.id}) }}'" style="background-color: {{ task.employee.color }}">

                    <td><div style="max-width:750px;word-break: break-all;">{{ task.label }}</div></td>
                    <td>{{ task.employee.email }}</td>
                    <td>{{ task.startAt ? task.startAt|localizeddate("medium", "short", "fr_FR") : '' }}</td>
                    <td>{{ task.endAt ? task.endAt|localizeddate("medium", "short", "fr_FR") : '' }}</td>
                    <td>
                        <span class="badge {{ task.done ? 'badge-success' : 'badge-danger' }}">
                            {{ task.done ? 'Terminé' : 'En attente' }}
                        </span>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Aucun enregistrement trouvé.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

templates/task/new.html.twig
 <div class="d-flex flex-column justify-content-center align-items-center">
    <h1>Créer une nouvelle tâche</h1>
    <div class="form-container w-50 p-4 rounded">
        {{ form_start(form) }}
        {{ form_row(form._token) }} <!-- CSRF -->
        {% if moreError is not empty %}<span class="alert alert-danger">{{ moreError }}</span>{% endif %}
        <div class="form-group mt-4">
            {% if form.vars.valid == false %}
                <div class="alert alert-danger no-list-style">{{ form_errors(form.label) }}</div>
            {% endif %}
            {{ form_widget(form.label) }}
        </div>
        <div class="form-group">
            <!-- Pour start_at et end_at ce format est utilisé pour transformer les datetime en string -->
            <div class="input-group">
                <input type="text"
                       class="form-control datetimePicker"
                       name="task[{{ form.start_at.vars.name }}]"
                       value="{{ form.start_at.vars.value | date("Y/m/d H:i") }}"
                       placeholder="{{ form.start_at.vars.attr.placeholder ?? "" }}"
                />
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon1">
                        <img width="16" height="16" src="{{ asset('images/_ionicons_svg_md-calendar.svg') }}"/>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <!-- Pour start_at et end_at ce format est utilisé pour transformer les datetime en string -->
            <div class="input-group">
                <input type="text"
                       class="form-control datetimePicker"
                       name="task[{{ form.end_at.vars.name }}]"
                       value="{{ form.end_at.vars.value | date("Y/m/d H:i") }}"
                       placeholder="{{ form.end_at.vars.attr.placeholder ?? "" }}"
                />
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon1">
                        <img width="16" height="16" src="{{ asset('images/_ionicons_svg_md-calendar.svg') }}"/>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            {{ form_row(form.employee) }}
        </div>
        <div class="form-group">
            {{ form_row(form.created_by) }}
        </div>

        <button class="btn btn-success">{{ button_label|default('Créer') }}</button>

        {{ form_end(form, { "render_rest": false }) }}
    </div>
</div>

<a href="{{ path('admin_list') }}">Revenir à la liste</a>

templates/task/show.html.twig
<div class="d-flex flex-column align-items-center">

    <h1>Tâche</h1>

    <table class="table w-50">
        <tbody>
            <tr>
                <th>Libellé</th>
                <td>{{ task.label }}</td>
            </tr>
            <tr>
                <th>Début</th>
                <td>{{ task.startAt ? task.startAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fin</th>
                <td>{{ task.endAt ? task.endAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Employe</th>
                <td>{{ task.employee }}</td>
            </tr>
            <tr>
                <th>Accompli</th>
                <td>
                    <span class="badge {{ task.done ? 'badge-success' : 'badge-danger' }}">
                        {{ task.done ? 'Terminé' : 'En attente' }}
                    </span>
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_list') }}">Revenir à la liste</a>

    <a href="{{ path('admin_edit', {'id': task.id}) }}">Modifier</a>

    {{ include('task/_delete_form.html.twig') }}
</div>